from typing import Any
from collections.abc import Iterator
from groq import Groq

from src.core.config import (
    GROQ_API_KEY,
    GROQ_MODEL,
    LLM_MAX_TOKENS,
    LLM_TEMPERATURE,
)

groq_client = Groq(api_key=GROQ_API_KEY)


def generate(messages: list[dict[str, Any]]) -> str:
    """
    Generate a completion from the configured Groq model.
    """

    try:
        response = groq_client.chat.completions.create(
            model=GROQ_MODEL,
            messages=messages,
            temperature=LLM_TEMPERATURE,
            max_completion_tokens=LLM_MAX_TOKENS,
        )

        content = response.choices[0].message.content

        return content.strip() if content else ""

    except Exception as exc:
        raise RuntimeError(
            f"Groq generation failed: {exc}"
        ) from exc



def stream(messages: list[dict[str, Any]]) -> Iterator[str]:
    """
    Stream a completion from the configured Groq model.

    Yields
    ------
    str
        Successive text fragments generated by the model.
    """

    try:
        response = groq_client.chat.completions.create(
            model=GROQ_MODEL,
            messages=messages,
            temperature=LLM_TEMPERATURE,
            max_completion_tokens=LLM_MAX_TOKENS,
            stream=True,
        )

        for chunk in response:
            if not chunk.choices:
                continue

            delta = chunk.choices[0].delta.content

            if delta:
                yield delta

    except Exception as exc:
        raise RuntimeError(
            f"Groq streaming failed: {exc}"
        ) from exc